_.templateSettings.interpolate = /{{([\s\S]+?)}}/g;

const navTpl = _.template('<nav><div class="nav-wrapper mlr30 center"><ul class="left navL"></ul><span class="navLogo">{{title}}</span><ul class="right navR"></ul></div></nav>'),
navSTpl = _.template('<li class="waves-effect waves-light"><a href="#" data-target="slide-out" class="sidenav-trigger material-icons">menu</a></li>'),
navLinkTpl = _.template('<li class="waves-effect waves-light"><a id="{{id}}" class="material-icons nlIcn" title="{{title}}">{{icn}}</a></li>'),
linkTpl = _.template('<li class="wow fadeInUp collection-item"><div class="collapsible-header waves-effect waves-dark"><i class="material-icons">chevron_right</i>{{name}}</div><div class="collapsible-body"><ul class="lnkGroup"><li class="lnkRow"><a id="lnk{{title}}" class="infoLink{{src}}"><span class="lnkText">view online</span><i class="material-icons lnkIcn">visibility</i></a></li><li class="lnkRow"><a href="./app/downloads/{{dir}}/{{title}}.docx" download><span class="lnkText">download word document</span><i class="material-icons lnkIcn">file_download</i></a></li><li class="lnkRow"><a href="./app/downloads/{{dir}}/{{title}}.pdf" download><span class="lnkText">download pdf document</span><i class="material-icons lnkIcn">file_download</i></a></li></ul></div></li>'),
lnkTpl = _.template('<li><a id="{{id}}" class="btn-floating {{color}}" title="{{title}}"><i class="material-icons">{{icn}}</i></a></li>'),
recentTpl = _.template('<ul id="{{id}}" class="collection with-header"><li class="collection-header"><h5>{{title}}</h5></li></ul>'),
footerTpl = _.template('<footer class="page-footer"><div class="footer-copyright"><div class="container">{{info}}</div></div></footer>'),
downloadTpl= _.template('<ul class="collapsible {{i}}dl"><li class="collection-header dHeader"><h4 class="ml10">{{e}}<i class="material-icons dIcnLnk">chevron_right</i></h4></li></ul>'),
sbHeadTpl = _.template('<div class="user-view"><h2>{{title}}</h2><h6>{{sub}}</h6><small>{{date}}</small></div>'),
sbLinkTpl = _.template('<li><div class="divider"></div></li><li class="ddLnk"><h4 class="ml10">{{i}}<i class="material-icons lnkIcn">chevron_right</i></h4></li><div class="sd{{i}}"></div>'),
floatTpl = _.template('<div class="fixed-action-btn"><a class="btn-floating btn-large abtn"><i class="large material-icons">settings</i></a><ul class="float-lnk"></ul></div>'),
hisCardTpl = _.template('<div class="col s6 m3"><div class="card hisCard"><div class="card-content"><p class="his-en">{{en}}</p><p class="his-cn">{{cn}}</p></div></div></div>'),
bcTpl = _.template('<div class="bcCard"><a class="breadcrumb">Home</a><a class="breadcrumb" id="bca" hidden></a><a id="bcb" class="breadcrumb" hidden></a></div>'),
translateTpl = _.template('<div id="translateMdl" class="modal bottom-sheet"><div class="modal-content"><h4>Translator</h4><div class="row"><div class="col s12 m6"><div class="input-field"><textarea id="src-translate" class="materialize-textarea validate" maxlength="50"></textarea><label>english</label><span id="translateHelper" class="helper-text" data-error="invalid" data-success="valid">status</span></div></div><div class="col s12 m6"><div class="input-field"><textarea id="dest-translate" class="materialize-textarea" readonly></textarea><label class="active">chinese</label></div></div><div class="col s12"><a id="translateBtn" class="waves-effect waves-light btn">translate</a></div><div class="col s12 mt4"><h4>History</h4><div id="transHis" class="row"></div></div></div></div><div class="modal-footer"><a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a></div></div>'),
chatboxTpl = _.template('<div id="chatroomMdl" class="modal bottom-sheet"><div class="modal-content"><h4>chatroom</h4><div class=""><iframe src="https://minnit.chat/XTU?embed&nickname={{name}}" style="border:none;width:100%;height:500px;" allowTransparency="true"></iframe></div><div class="modal-footer"><a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a></div></div>'),
studentModalTpl = _.template('<div id="studentModal" class="modal"><div class="modal-content"><div class="container"><h4 class="center">Enter your student details</h4><div class="input-field"><input id="student-id" type="text" class="validate"><label>student id</label></div><div class="input-field"><input id="student-name" type="text" class="validate"><label>Name</label></div><div class="input-field"><input id="student-email" type="email" class="validate"><label>Email</label></div></div></div><div class="modal-footer"><button id="student-btn" type="button" class="waves-effect waves-light btn-flat">Submit</a></div></div>');
